import { describe, expect, test } from "bun:test";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { EnvVarContract } from "./contracts/common.ts";
import { envNamesIn, missingRequiredEnv } from "./env.ts";

function envFile(content: string): string {
  const root = mkdtempSync(join(tmpdir(), "groot-env-"));
  writeFileSync(join(root, ".env.local"), content);
  return root;
}

describe("envNamesIn — names a dotenv file sets, as Bun loads it", () => {
  test("assignments with a value count; blank values, comments, and junk lines do not", () => {
    const root = envFile(
      [
        "SET_PLAIN=value",
        "export SET_EXPORTED=1",
        "SET_COLON: yes",
        'SET_QUOTED="has # hash"',
        "EMPTY=",
        "EMPTY_COMMENT= # set me",
        'EMPTY_DOUBLE=""',
        "EMPTY_SINGLE=''",
        "EMPTY_BACKTICK=``",
        "BLANK_SPACES=   ",
        "# COMMENTED=out",
        "not an assignment",
      ].join("\n"),
    );
    expect([...envNamesIn(root, ".env.local")].sort()).toEqual([
      "SET_COLON",
      "SET_EXPORTED",
      "SET_PLAIN",
      "SET_QUOTED",
    ]);
  });

  test("the last assignment wins, so a later blank value unsets an earlier one", () => {
    const root = envFile("TOKEN=abc\nTOKEN=\n");
    expect(envNamesIn(root, ".env.local").has("TOKEN")).toBe(false);
  });

  test("a missing file sets nothing", () => {
    const root = mkdtempSync(join(tmpdir(), "groot-env-"));
    expect(envNamesIn(root, ".env.local").size).toBe(0);
  });

  test("a required variable with a blank value is reported missing", () => {
    const root = envFile("BETTER_AUTH_SECRET= # generated by groot\n");
    const contract: EnvVarContract = {
      name: "BETTER_AUTH_SECRET",
      consumer: ".",
      scope: "server",
      sensitivity: "secret",
      required: true,
      description: "session signing secret",
      storage: ".env.local",
      example: "",
      generate: "random-secret",
      declaredBy: "test",
    };
    expect(missingRequiredEnv(root, [contract]).map((entry) => entry.name)).toEqual([
      "BETTER_AUTH_SECRET",
    ]);
  });
});
