/**
 * Secret values stay out of `.groot/` across operations: a value an earlier
 * operation generated, or one a blueprint contract declares secret, is
 * concealed in a later operation's backups and plan copy and redacted from
 * its logs — while rollback and resume still restore and read them exactly.
 * Operation state is owner-only (directories 0700; plan copies, backups,
 * and logs 0600).
 */
import { afterAll, describe, expect, test } from "bun:test";
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { EnvVarContract } from "../contracts/common.ts";
import { blueprintFixture } from "../test-fixtures.ts";
import { applyPlan, readOperation, rollbackOperation } from "./index.ts";
import {
  addCommand,
  addSecret,
  allFiles,
  anyFileContains,
  buildPlan,
  operationDir,
  permissive,
  removeScratchDirs,
  scratchProject,
  snapshot,
  testContext,
} from "./test-support.ts";

afterAll(removeScratchDirs);

async function apply(root: string, plan: Awaited<ReturnType<typeof buildPlan>>) {
  return applyPlan(testContext(root).ctx, { plan, root, policy: permissive, command: "apply" });
}

const mode = (path: string): number => statSync(path).mode & 0o777;

describe("secrets of earlier operations and blueprint contracts", () => {
  test("a secret generated by an earlier operation never reaches a later one's backups, logs, or plan copy", async () => {
    // Arrange — op1 generates SESSION_KEY (a name no redaction pattern knows).
    const root = scratchProject({ ".env.local": "EXISTING=1\n", "config.txt": "port=3000\n" });
    await apply(
      root,
      await buildPlan(root, async (b) => {
        addSecret(b, ".env.local", "SESSION_KEY");
      }),
    );
    const secret = /SESSION_KEY=(\S+)/.exec(readFileSync(join(root, ".env.local"), "utf8"))?.[1];
    if (secret === undefined) throw new Error("no secret generated");
    writeFileSync(join(root, "config.txt"), `port=3000\nkey=${secret}\n`); // a human copies it
    const before = snapshot(root);

    // Act — op2, a different plan, edits a file holding it and prints .env.local.
    const op2 = await apply(
      root,
      await buildPlan(root, async (b) => {
        await b.editFile({
          path: "config.txt",
          edit: { kind: "lines", lines: ["debug=false"], header: null },
          description: "add debug to config.txt",
          owns: [],
          createIfMissing: false,
        });
        addCommand(b, "echo '# touched' >> .env.local; cat .env.local", {
          touches: [".env.local"],
          description: "touch and print .env.local",
        });
      }),
    );
    const leak = anyFileContains(join(root, ".groot"), secret);
    const shown = await readOperation(root, op2.operationId);
    await rollbackOperation(testContext(root).ctx, root, op2.operationId);

    // Assert
    expect(leak).toBeNull();
    expect(shown.status).toBe("completed");
    expect(snapshot(root)).toEqual(before);
  });

  test("a value a blueprint contract declares secret is concealed and redacted", async () => {
    // Arrange
    const password = "Pg-Pr0d-Passw0rd-123";
    const root = scratchProject({ ".env": `DATABASE_URL=postgres://app:${password}@db/app\n` });
    const contract: EnvVarContract = {
      name: "DATABASE_URL",
      consumer: ".",
      scope: "server",
      sensitivity: "secret",
      required: true,
      description: "database",
      storage: ".env",
      example: "postgres://user:pass@localhost/app",
      generate: "none",
      declaredBy: "test",
    };
    writeFileSync(
      join(root, "groot.json"),
      JSON.stringify(blueprintFixture({ environment: [contract] })),
    );
    const before = snapshot(root);

    // Act
    const applied = await apply(
      root,
      await buildPlan(root, async (b) => {
        addCommand(b, "echo 'PORT=1' >> .env; cat .env", {
          touches: [".env"],
          description: "touch and print .env",
        });
      }),
    );
    const leak = anyFileContains(join(root, ".groot"), password);
    await rollbackOperation(testContext(root).ctx, root, applied.operationId);

    // Assert
    expect(leak).toBeNull();
    expect(snapshot(root)).toEqual(before);
  });
});

describe("operation state is owner-only", () => {
  test("operation directories are 0700; plan copies, backups, and logs 0600", async () => {
    // Arrange
    const root = scratchProject({ "notes.txt": "public\n" });
    const plan = await buildPlan(root, async (b) => {
      addCommand(b, "echo more >> notes.txt", { touches: ["notes.txt"] });
    });

    // Act
    const applied = await apply(root, plan);
    const dir = operationDir(root, applied.operationId);

    // Assert
    for (const sub of ["", "backups", "logs"]) expect(mode(join(dir, sub))).toBe(0o700);
    expect(mode(join(dir, "plan.json"))).toBe(0o600);
    for (const file of allFiles(join(dir, "backups"))) expect(mode(file)).toBe(0o600);
    for (const file of allFiles(join(dir, "logs"))) expect(mode(file)).toBe(0o600);
  });

  test("restoring a 0600 backup still gives the file its original mode", async () => {
    // Arrange
    const root = scratchProject({ "notes.txt": "public\n" });
    const before = snapshot(root);
    const plan = await buildPlan(root, async (b) => {
      addCommand(b, "echo more >> notes.txt", { touches: ["notes.txt"] });
    });
    const applied = await apply(root, plan);

    // Act
    await rollbackOperation(testContext(root).ctx, root, applied.operationId);

    // Assert
    expect(snapshot(root)).toEqual(before);
    expect(mode(join(root, "notes.txt"))).toBe(before["notes.txt"]?.mode ?? -1);
  });
});
