/**
 * Secret values stay out of `.groot/` across operations: a value an earlier
 * operation generated, or one a blueprint contract declares secret, is
 * concealed in a later operation's backups and plan copy, and in saved
 * plans, and redacted from its logs — while rollback, resume, and loading
 * still restore and read them exactly. Once a quoted value changes, the
 * operation stays listed and readable and rolls back as far as its backups
 * allow (it is never resumed), and a saved plan quoting it is stale.
 * Operation state is owner-only (directories 0700; plan copies, backups,
 * and logs 0600).
 */
import { afterAll, describe, expect, test } from "bun:test";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { EnvVarContract } from "../contracts/common.ts";
import type { OperationPlan } from "../contracts/plan.ts";
import { GrootV2Error } from "../errors.ts";
import { blueprintFixture } from "../test-fixtures.ts";
import {
  applyPlan,
  listOperations,
  loadPlanFile,
  loadSavedPlan,
  previewRollback,
  readOperation,
  resumeOperation,
  rollbackOperation,
  savePlan,
} from "./index.ts";
import {
  addCommand,
  addSecret,
  allFiles,
  anyFileContains,
  buildPlan,
  operationDir,
  permissive,
  removeScratchDirs,
  scratchProject,
  snapshot,
  testContext,
} from "./test-support.ts";

afterAll(removeScratchDirs);

async function apply(root: string, plan: Awaited<ReturnType<typeof buildPlan>>) {
  return applyPlan(testContext(root).ctx, { plan, root, policy: permissive, command: "apply" });
}

const mode = (path: string): number => statSync(path).mode & 0o777;

describe("secrets of earlier operations and blueprint contracts", () => {
  test("a secret generated by an earlier operation never reaches a later one's backups, logs, or plan copy", async () => {
    // Arrange — op1 generates SESSION_KEY (a name no redaction pattern knows).
    const root = scratchProject({ ".env.local": "EXISTING=1\n", "config.txt": "port=3000\n" });
    await apply(
      root,
      await buildPlan(root, async (b) => {
        addSecret(b, ".env.local", "SESSION_KEY");
      }),
    );
    const secret = /SESSION_KEY=(\S+)/.exec(readFileSync(join(root, ".env.local"), "utf8"))?.[1];
    if (secret === undefined) throw new Error("no secret generated");
    writeFileSync(join(root, "config.txt"), `port=3000\nkey=${secret}\n`); // a human copies it
    const before = snapshot(root);

    // Act — op2, a different plan, edits a file holding it and prints .env.local.
    const op2 = await apply(
      root,
      await buildPlan(root, async (b) => {
        await b.editFile({
          path: "config.txt",
          edit: { kind: "lines", lines: ["debug=false"], header: null },
          description: "add debug to config.txt",
          owns: [],
          createIfMissing: false,
        });
        addCommand(b, "echo '# touched' >> .env.local; cat .env.local", {
          touches: [".env.local"],
          description: "touch and print .env.local",
        });
      }),
    );
    const leak = anyFileContains(join(root, ".groot"), secret);
    const shown = await readOperation(root, op2.operationId);
    await rollbackOperation(testContext(root).ctx, root, op2.operationId);

    // Assert
    expect(leak).toBeNull();
    expect(shown.status).toBe("completed");
    expect(snapshot(root)).toEqual(before);
  });

  test("a value a blueprint contract declares secret is concealed and redacted", async () => {
    // Arrange
    const password = "Pg-Pr0d-Passw0rd-123";
    const root = scratchProject({ ".env": `DATABASE_URL=postgres://app:${password}@db/app\n` });
    const contract: EnvVarContract = {
      name: "DATABASE_URL",
      consumer: ".",
      scope: "server",
      sensitivity: "secret",
      required: true,
      description: "database",
      storage: ".env",
      example: "postgres://user:pass@localhost/app",
      generate: "none",
      declaredBy: "test",
    };
    writeFileSync(
      join(root, "groot.json"),
      JSON.stringify(blueprintFixture({ environment: [contract] })),
    );
    const before = snapshot(root);

    // Act
    const applied = await apply(
      root,
      await buildPlan(root, async (b) => {
        addCommand(b, "echo 'PORT=1' >> .env; cat .env", {
          touches: [".env"],
          description: "touch and print .env",
        });
      }),
    );
    const leak = anyFileContains(join(root, ".groot"), password);
    await rollbackOperation(testContext(root).ctx, root, applied.operationId);

    // Assert
    expect(leak).toBeNull();
    expect(snapshot(root)).toEqual(before);
  });
});

/** op1 generates SESSION_KEY into .env.local; returns the value and the file's text. */
async function generatedSecret(root: string): Promise<{ secret: string; envText: string }> {
  await apply(
    root,
    await buildPlan(root, async (b) => {
      addSecret(b, ".env.local", "SESSION_KEY");
    }),
  );
  const envText = readFileSync(join(root, ".env.local"), "utf8");
  const secret = /SESSION_KEY=(\S+)/.exec(envText)?.[1];
  if (secret === undefined) throw new Error("no secret generated");
  return { secret, envText };
}

const ROTATED = "EXISTING=1\nSESSION_KEY=rotated-value-0123456789abcdef\n";

async function expectGrootError(promise: Promise<unknown>): Promise<GrootV2Error> {
  try {
    await promise;
  } catch (error) {
    expect(error).toBeInstanceOf(GrootV2Error);
    return error as GrootV2Error;
  }
  throw new Error("expected a GrootV2Error");
}

describe("plan copies quoting a secret whose value changes later", () => {
  test("the operation stays listed and readable; rollback waits only for the value a backup quotes", async () => {
    // Arrange — a human copies op1's secret into config.txt; op2's exact preview quotes it.
    const root = scratchProject({ ".env.local": "EXISTING=1\n", "config.txt": "port=3000\n" });
    const { secret, envText } = await generatedSecret(root);
    writeFileSync(join(root, "config.txt"), `port=3000\nkey=${secret}\n`);
    const before = snapshot(root);
    const op2 = await apply(
      root,
      await buildPlan(root, async (b) => {
        await b.editFile({
          path: "config.txt",
          edit: { kind: "lines", lines: ["debug=false"], header: null },
          description: "add debug to config.txt",
          owns: [],
          createIfMissing: false,
        });
        await b.writeFile({
          path: "other.txt",
          content: "other\n",
          description: "create other.txt",
        });
      }),
    );
    writeFileSync(join(root, ".env.local"), ROTATED); // the user rotates the key

    // Act
    const listed = (await listOperations(root)).map((state) => state.operationId);
    const shown = await readOperation(root, op2.operationId);
    const preview = await previewRollback(testContext(root).ctx, root, op2.operationId);
    writeFileSync(join(root, ".env.local"), envText); // ...and puts it back
    const rolledBack = await rollbackOperation(testContext(root).ctx, root, op2.operationId);

    // Assert
    expect(listed).toContain(op2.operationId);
    expect(shown.status).toBe("completed");
    expect(preview.conflicts).toEqual(["config.txt"]);
    const conflict = preview.steps.find((step) => step.action === "conflict");
    expect(conflict?.reason).toContain("quotes SESSION_KEY (.env.local)");
    expect(rolledBack.status).toBe("rolled-back");
    expect(snapshot(root)).toEqual(before);
    expect(anyFileContains(join(root, ".groot"), secret)).toBeNull();
  });

  test("an interrupted operation whose plan quotes a changed value is not resumable, yet rolls back", async () => {
    // Arrange — op2 writes copy.txt quoting the secret (exact preview), then other.txt.
    const root = scratchProject({ ".env.local": "EXISTING=1\n" });
    const { secret } = await generatedSecret(root);
    const plan = await buildPlan(root, async (b) => {
      await b.writeFile({ path: "copy.txt", content: `key=${secret}\n`, description: "copy" });
      await b.writeFile({ path: "other.txt", content: "other\n", description: "create other.txt" });
    });
    const run = testContext(root, (event) => {
      if (event.type === "step.done" && event.stepId === "s01") run.controller.abort("SIGINT");
    });
    const interrupted = await expectGrootError(
      applyPlan(run.ctx, { plan, root, policy: permissive, command: "apply" }),
    );
    const operationId = String(interrupted.details?.operationId);
    writeFileSync(join(root, ".env.local"), ROTATED);

    // Act
    const shown = await readOperation(root, operationId);
    const resumed = await expectGrootError(
      resumeOperation(testContext(root).ctx, root, operationId),
    );
    const rolledBack = await rollbackOperation(testContext(root).ctx, root, operationId);

    // Assert
    expect(interrupted.id).toBe("GROOT_E_INTERRUPTED");
    expect(shown.status).toBe("interrupted");
    expect(shown.resumable).toBe(false);
    expect(resumed.id).toBe("GROOT_E_CONFLICT");
    expect(resumed.message).toContain("SESSION_KEY");
    expect(rolledBack.status).toBe("rolled-back");
    expect(existsSync(join(root, "copy.txt"))).toBe(false);
    expect(existsSync(join(root, "other.txt"))).toBe(false);
  });
});

describe("saved plans", () => {
  async function planQuotingSecret(root: string): Promise<{ plan: OperationPlan; secret: string }> {
    const { secret } = await generatedSecret(root);
    writeFileSync(join(root, "config.txt"), `port=3000\nkey=${secret}\n`);
    const plan = await buildPlan(root, async (b) => {
      await b.editFile({
        path: "config.txt",
        edit: { kind: "lines", lines: ["debug=false"], header: null },
        description: "add debug to config.txt",
        owns: [],
        createIfMissing: false,
      });
    });
    return { plan, secret };
  }

  test("a saved plan quoting a known secret keeps it out of .groot/plans and loads back exactly", async () => {
    // Arrange
    const root = scratchProject({ ".env.local": "EXISTING=1\n", "config.txt": "port=3000\n" });
    const { plan, secret } = await planQuotingSecret(root);

    // Act
    const path = await savePlan(root, plan);
    const leak = anyFileContains(join(root, ".groot"), secret);
    const byId = await loadSavedPlan(root, plan.planId);
    const byPath = await loadPlanFile(path); // how `groot apply <path>` and the MCP plan tools read it

    // Assert
    expect(leak).toBeNull();
    expect(byId).toEqual(plan);
    expect(byPath).toEqual(plan);
    for (const file of allFiles(join(root, ".groot/plans"))) expect(mode(file)).toBe(0o600);
  });

  test("once the value it quotes changes, a saved plan is stale, naming where the value lived", async () => {
    // Arrange
    const root = scratchProject({ ".env.local": "EXISTING=1\n", "config.txt": "port=3000\n" });
    const { plan } = await planQuotingSecret(root);
    await savePlan(root, plan);
    writeFileSync(join(root, ".env.local"), ROTATED);

    // Act
    const error = await expectGrootError(loadSavedPlan(root, plan.planId));

    // Assert
    expect(error.id).toBe("GROOT_E_STALE_PLAN");
    const findings = (error.details?.findings ?? []) as { path: string }[];
    expect(findings.map((finding) => finding.path)).toEqual([".env.local"]);
  });
});

describe("operation state is owner-only", () => {
  test("operation directories are 0700; plan copies, backups, and logs 0600", async () => {
    // Arrange
    const root = scratchProject({ "notes.txt": "public\n" });
    const plan = await buildPlan(root, async (b) => {
      addCommand(b, "echo more >> notes.txt", { touches: ["notes.txt"] });
    });

    // Act
    const applied = await apply(root, plan);
    const dir = operationDir(root, applied.operationId);

    // Assert
    for (const sub of ["", "backups", "logs"]) expect(mode(join(dir, sub))).toBe(0o700);
    expect(mode(join(dir, "plan.json"))).toBe(0o600);
    for (const file of allFiles(join(dir, "backups"))) expect(mode(file)).toBe(0o600);
    for (const file of allFiles(join(dir, "logs"))) expect(mode(file)).toBe(0o600);
  });

  test("restoring a 0600 backup still gives the file its original mode", async () => {
    // Arrange
    const root = scratchProject({ "notes.txt": "public\n" });
    const before = snapshot(root);
    const plan = await buildPlan(root, async (b) => {
      addCommand(b, "echo more >> notes.txt", { touches: ["notes.txt"] });
    });
    const applied = await apply(root, plan);

    // Act
    await rollbackOperation(testContext(root).ctx, root, applied.operationId);

    // Assert
    expect(snapshot(root)).toEqual(before);
    expect(mode(join(root, "notes.txt"))).toBe(before["notes.txt"]?.mode ?? -1);
  });
});
