/**
 * groot.lock.json from the scaffold pipeline (engine/locks.ts): every entry
 * keeps the exact resolution that produced its scaffolds, offline runs are
 * recorded as unresolved, an unreadable lock is a clean stitch failure, the
 * lock is only ever written inside the workspace, and a registry miss keeps
 * init/add's v1 exit code. Registry answers come from fixture fetches —
 * nothing here touches the network.
 */
import { describe, expect, test } from "bun:test";
import { existsSync, lstatSync, readFileSync, symlinkSync } from "node:fs";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { emptyLock, serializeLock } from "../core/blueprint/index.ts";
import { type GeneratorLock, GrootLock } from "../core/contracts/lock.ts";
import { GrootV2Error } from "../core/errors.ts";
import { EXIT, GrootError } from "./errors.ts";
import { assertLockReadable, exactArgv, resolveGenerators, stitchLock } from "./locks.ts";
import type { Plan, PlannedScaffold } from "./types.ts";

const NOW = "2026-10-08T12:00:00.000Z";
const LATER = "2026-10-09T08:30:00.000Z";

const OPTIONS = {
  install: false,
  git: false,
  dirConflict: "error",
  keepFailed: false,
  verbose: false,
} as const;

const NEXT_WEB: PlannedScaffold = {
  slot: "web",
  framework: "next",
  path: "apps/web",
  generator: "create-next-app@16",
  port: 3000,
};

function hono(path: string): PlannedScaffold {
  return { slot: "api", framework: "hono", path, generator: "create-hono@0.19", port: 3001 };
}

/** create-hono@0.19 resolved to an exact version, as the registry reports it. */
function exact(version: string, usedBy: string[], resolvedAt = NOW): GeneratorLock {
  return {
    package: "create-hono",
    range: "0.19",
    version,
    integrity: `sha512-${version}`,
    tarball: `https://registry.npmjs.org/create-hono/-/create-hono-${version}.tgz`,
    resolvedAt,
    source: "npm-registry",
    usedBy,
  };
}

/** create-hono@0.19 resolved while the registry was unreachable (or by an offline migration). */
function offline(usedBy: string[]): GeneratorLock {
  return {
    package: "create-hono",
    range: "0.19",
    version: null,
    integrity: null,
    tarball: null,
    resolvedAt: NOW,
    source: "unresolved",
    usedBy,
  };
}

/** A workspace root whose groot.lock.json records `generators` (null: no lock yet). */
async function workspace(generators: GeneratorLock[] | null): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "groot-locks-"));
  if (generators !== null) {
    await writeFile(join(root, "groot.lock.json"), serializeLock({ ...emptyLock(), generators }));
  }
  return root;
}

/** A v2 plan over `scaffolds`, carrying this run's resolutions (as init/add pass them). */
function plan(root: string, scaffolds: PlannedScaffold[], generatorLocks?: GeneratorLock[]): Plan {
  return {
    name: "grown",
    targetDir: root,
    createdWith: "create-groot@0.1.0-test",
    conventions: { packagesNamespace: "@repo" },
    scaffolds,
    options: OPTIONS,
    manifestVersion: 2,
    generatorLocks,
  };
}

/** The lock's generator entries as [package, version, integrity, source, usedBy]. */
function recorded(root: string): unknown[][] {
  const lock = GrootLock.parse(JSON.parse(readFileSync(join(root, "groot.lock.json"), "utf8")));
  return lock.generators.map((entry) => [
    entry.package,
    entry.version,
    entry.integrity,
    entry.source,
    entry.usedBy,
  ]);
}

function errorOf(fn: () => unknown): unknown {
  try {
    fn();
  } catch (error) {
    return error;
  }
  throw new Error("expected an error");
}

async function rejectionOf(promise: Promise<unknown>): Promise<unknown> {
  try {
    await promise;
  } catch (error) {
    return error;
  }
  throw new Error("expected a rejection");
}

describe("stitchLock — one entry per resolution (a scaffold keeps what produced it)", () => {
  test("a newer resolution for a second scaffold gets its own entry; the first keeps its version and integrity", async () => {
    // Arrange — apps/api was generated by 0.19.4; the registry now answers 0.19.5.
    const root = await workspace([exact("0.19.4", ["apps/api"])]);

    // Act
    stitchLock(plan(root, [hono("apps/api"), hono("apps/api2")], [exact("0.19.5", ["apps/api2"])]));

    // Assert
    expect(recorded(root)).toEqual([
      ["create-hono", "0.19.4", "sha512-0.19.4", "npm-registry", ["apps/api"]],
      ["create-hono", "0.19.5", "sha512-0.19.5", "npm-registry", ["apps/api2"]],
    ]);
  });

  test("an offline add is its own unresolved entry — never recorded as exact", async () => {
    // Arrange
    const root = await workspace([exact("0.19.4", ["apps/api"])]);

    // Act — the generator ran from the series (`create-hono@0.19`), not from 0.19.4.
    stitchLock(plan(root, [hono("apps/api"), hono("apps/api2")], [offline(["apps/api2"])]));

    // Assert
    expect(recorded(root)).toEqual([
      ["create-hono", "0.19.4", "sha512-0.19.4", "npm-registry", ["apps/api"]],
      ["create-hono", null, null, "unresolved", ["apps/api2"]],
    ]);
  });

  test("an unresolved entry (a migrated workspace) stays unresolved for its scaffold", async () => {
    // Arrange
    const root = await workspace([offline(["apps/api"])]);

    // Act
    stitchLock(plan(root, [hono("apps/api"), hono("apps/api2")], [exact("0.19.5", ["apps/api2"])]));

    // Assert
    expect(recorded(root)).toEqual([
      ["create-hono", null, null, "unresolved", ["apps/api"]],
      ["create-hono", "0.19.5", "sha512-0.19.5", "npm-registry", ["apps/api2"]],
    ]);
  });

  test("the same resolution shares one entry, and stitching again changes nothing", async () => {
    // Arrange
    const root = await workspace([exact("0.19.4", ["apps/api"])]);
    const grown = plan(
      root,
      [hono("apps/api"), hono("apps/api2")],
      [exact("0.19.4", ["apps/api2"], LATER)],
    );

    // Act
    stitchLock(grown);
    const written = readFileSync(join(root, "groot.lock.json"), "utf8");
    const again = stitchLock(grown);

    // Assert
    expect(recorded(root)).toEqual([
      ["create-hono", "0.19.4", "sha512-0.19.4", "npm-registry", ["apps/api", "apps/api2"]],
    ]);
    expect(again).toBeNull();
    expect(readFileSync(join(root, "groot.lock.json"), "utf8")).toBe(written);
  });

  test("a scaffold generated again moves to the resolution that produced it; an emptied entry is dropped", async () => {
    // Arrange
    const shared = await workspace([exact("0.19.4", ["apps/api", "apps/edge"])]);
    const alone = await workspace([exact("0.19.4", ["apps/api"])]);

    // Act
    stitchLock(
      plan(shared, [hono("apps/api"), hono("apps/edge")], [exact("0.19.5", ["apps/api"])]),
    );
    stitchLock(plan(alone, [hono("apps/api")], [exact("0.19.5", ["apps/api"])]));

    // Assert
    expect(recorded(shared)).toEqual([
      ["create-hono", "0.19.4", "sha512-0.19.4", "npm-registry", ["apps/edge"]],
      ["create-hono", "0.19.5", "sha512-0.19.5", "npm-registry", ["apps/api"]],
    ]);
    expect(recorded(alone)).toEqual([
      ["create-hono", "0.19.5", "sha512-0.19.5", "npm-registry", ["apps/api"]],
    ]);
  });

  test("scaffolds the lock doesn't record yet are added as unresolved, per scaffold", async () => {
    // Arrange — a v2 workspace without a lock grows a second hono app.
    const root = await workspace(null);

    // Act
    stitchLock(
      plan(root, [NEXT_WEB, hono("apps/api"), hono("apps/api2")], [exact("0.19.5", ["apps/api2"])]),
    );

    // Assert — apps/api is not claimed by apps/api2's resolution.
    expect(recorded(root)).toEqual([
      ["create-hono", "0.19.5", "sha512-0.19.5", "npm-registry", ["apps/api2"]],
      ["create-next-app", null, null, "unresolved", ["apps/web"]],
      ["create-hono", null, null, "unresolved", ["apps/api"]],
    ]);
  });
});

describe("stitchLock — reading and writing groot.lock.json", () => {
  test.each([
    ["merge-conflict markers", "<<<<<<< HEAD\n{}\n=======\n{}\n>>>>>>> theirs\n"],
    [
      "a newer lockVersion",
      JSON.stringify({ ...emptyLock(), lockVersion: 2, generatedBy: "create-groot@9.0.0" }),
    ],
    ["a field this groot doesn't know", JSON.stringify({ ...emptyLock(), tools: [] })],
  ])("a lock with %s is a stitch failure naming the file, never a raw parse error", async (_label, text) => {
    // Arrange
    const root = await workspace(null);
    await writeFile(join(root, "groot.lock.json"), text);

    // Act
    const error = errorOf(() =>
      stitchLock(plan(root, [hono("apps/api")], [exact("0.19.5", ["apps/api"])])),
    );

    // Assert
    expect(error).toBeInstanceOf(GrootError);
    expect((error as GrootError).exitCode).toBe(EXIT.STITCH);
    expect((error as GrootError).message).toContain("groot.lock.json");
    expect((error as GrootError).hint).toBeDefined();
    expect(readFileSync(join(root, "groot.lock.json"), "utf8")).toBe(text);
  });

  test.skipIf(process.platform === "win32")(
    "a lock symlinked outside the workspace is refused — nothing is written through the link",
    async () => {
      // Arrange — groot.lock.json → ../outside/lock.json (dangling at first).
      const base = await mkdtemp(join(tmpdir(), "groot-locks-link-"));
      const root = join(base, "ws");
      const outside = join(base, "outside", "lock.json");
      await mkdir(root);
      await mkdir(join(base, "outside"));
      symlinkSync("../outside/lock.json", join(root, "groot.lock.json"));
      const grow = () =>
        stitchLock(plan(root, [hono("apps/api")], [exact("0.19.5", ["apps/api"])]));

      // Act
      const dangling = errorOf(grow);
      const foreign = serializeLock({ ...emptyLock(), generators: [exact("0.19.4", ["x"])] });
      await writeFile(outside, foreign);
      const existing = errorOf(grow);

      // Assert — refused both times; the outside file is neither created nor rewritten.
      for (const error of [dangling, existing]) {
        expect(error).toBeInstanceOf(GrootError);
        expect((error as GrootError).exitCode).toBe(EXIT.STITCH);
        expect((error as GrootError).message).toContain("groot.lock.json");
      }
      expect(readFileSync(outside, "utf8")).toBe(foreign);
      expect(lstatSync(join(root, "groot.lock.json")).isSymbolicLink()).toBe(true);
    },
  );

  test("v1 workspaces never get a lock", async () => {
    // Arrange
    const root = await workspace(null);

    // Act
    const note = stitchLock({ ...plan(root, [hono("apps/api")]), manifestVersion: 1 });

    // Assert
    expect(note).toBeNull();
    expect(existsSync(join(root, "groot.lock.json"))).toBe(false);
  });
});

describe("assertLockReadable — refused before anything is generated", () => {
  test.each([
    [
      "merge-conflict markers",
      "<<<<<<< HEAD\n{}\n=======\n{}\n>>>>>>> theirs\n",
      "GROOT_E_INVALID_DOCUMENT",
    ],
    [
      "a newer lockVersion",
      JSON.stringify({ ...emptyLock(), lockVersion: 2 }),
      "GROOT_E_UNSUPPORTED_SCHEMA",
    ],
    [
      "a field this groot doesn't know",
      JSON.stringify({ ...emptyLock(), tools: [] }),
      "GROOT_E_INVALID_DOCUMENT",
    ],
  ])("a lock with %s is a usage error (exit 2) naming the file, with a hint", async (_label, text, id) => {
    // Arrange
    const root = await workspace(null);
    await writeFile(join(root, "groot.lock.json"), text);

    // Act
    const error = await rejectionOf(assertLockReadable(plan(root, [hono("apps/api")])));

    // Assert
    expect(error).toBeInstanceOf(GrootV2Error);
    expect((error as GrootV2Error).id).toBe(id as GrootV2Error["id"]);
    expect((error as GrootV2Error).exitCode).toBe(EXIT.USAGE);
    expect((error as GrootV2Error).message).toContain("groot.lock.json");
    expect((error as GrootV2Error).hint).toBeDefined();
  });

  test.skipIf(process.platform === "win32")(
    "a lock symlinked outside the workspace is refused up front (exit 2)",
    async () => {
      // Arrange
      const base = await mkdtemp(join(tmpdir(), "groot-locks-link-"));
      const root = join(base, "ws");
      await mkdir(root);
      symlinkSync("../outside.json", join(root, "groot.lock.json"));

      // Act
      const error = await rejectionOf(assertLockReadable(plan(root, [hono("apps/api")])));

      // Assert
      expect(error).toBeInstanceOf(GrootV2Error);
      expect((error as GrootV2Error).id).toBe("GROOT_E_PATH_OUTSIDE_PROJECT");
      expect((error as GrootV2Error).exitCode).toBe(EXIT.USAGE);
    },
  );

  test("an absent or valid lock passes; a v1 workspace's lock is never read (v1 gets none)", async () => {
    // Arrange
    const absent = await workspace(null);
    const valid = await workspace([exact("0.19.4", ["apps/api"])]);
    const v1 = await workspace(null);
    await writeFile(join(v1, "groot.lock.json"), "not json");
    // init's target may not exist yet, or be a file in the way (merge policy).
    const notYet = join(absent, "fresh");
    const file = join(absent, "a-file");
    await writeFile(file, "x");

    // Act / Assert
    await assertLockReadable(plan(absent, [hono("apps/api")]));
    await assertLockReadable(plan(valid, [hono("apps/api")]));
    await assertLockReadable({ ...plan(v1, [hono("apps/api")]), manifestVersion: 1 });
    await assertLockReadable(plan(notYet, [hono("apps/api")]));
    await assertLockReadable(plan(file, [hono("apps/api")]));
  });
});

describe("resolveGenerators — registry answers keep init/add's v1 exit codes", () => {
  const packument = {
    "dist-tags": { latest: "0.20.0" },
    versions: { "0.20.0": { dist: { integrity: "sha512-0.20.0" } } },
  };
  const respond = (response: () => Response | Promise<Response>): typeof fetch =>
    (async () => response()) as unknown as typeof fetch;
  const json = (value: unknown, status = 200) =>
    new Response(JSON.stringify(value), {
      status,
      headers: { "content-type": "application/json" },
    });
  const apiPlan = plan("/tmp/groot-locks-unused", [hono("apps/api")]);

  test("no published version in the pinned series is a generator failure (exit 4), with the registry's message and hint", async () => {
    // Act
    const error = await rejectionOf(
      resolveGenerators(apiPlan, { includeTrunk: false, fetch: respond(() => json(packument)) }),
    );

    // Assert
    expect(error).toBeInstanceOf(GrootError);
    expect((error as GrootError).exitCode).toBe(EXIT.GENERATOR);
    expect((error as GrootError).message).toBe(
      'No published version of create-hono matches "0.19" (latest is 0.20.0).',
    );
    expect((error as GrootError).hint).toContain("update the pin");
  });

  test("a package the registry doesn't have (404) is a generator failure too", async () => {
    // Act
    const error = await rejectionOf(
      resolveGenerators(apiPlan, { includeTrunk: false, fetch: respond(() => json({}, 404)) }),
    );

    // Assert
    expect(error).toBeInstanceOf(GrootError);
    expect((error as GrootError).exitCode).toBe(EXIT.GENERATOR);
    expect((error as GrootError).message).toContain('no package "create-hono"');
  });

  test("an unreachable registry never fails: the entry is unresolved and the series runs", async () => {
    // Act
    const locks = await resolveGenerators(apiPlan, {
      includeTrunk: false,
      fetch: respond(() => Promise.reject(new TypeError("fetch failed"))),
    });

    // Assert
    expect(locks).toHaveLength(1);
    expect(locks[0]).toMatchObject({
      package: "create-hono",
      range: "0.19",
      version: null,
      source: "unresolved",
      usedBy: ["apps/api"],
    });
    expect(exactArgv(["bunx", "create-hono@0.19", "apps/api"], locks)).toEqual([
      "bunx",
      "create-hono@0.19",
      "apps/api",
    ]);
  });
});
