/**
 * The managed AGENTS.md section: a concise, deterministic project map
 * generated from the blueprint (desired state) and discovery (observed
 * scripts). No timestamps or volatile values, so re-syncing an unchanged
 * project is a no-op. Package names are backticked (an unquoted `@name`
 * reads as an import to Claude Code), and secret VALUES never appear —
 * only variable names and where they live.
 */
import type { BlueprintV2 } from "../contracts/blueprint.ts";
import type { ProjectObservation } from "../contracts/project.ts";

export const AGENTS_REGION_ID = "project-context";
export const CLAUDE_IMPORT_REGION_ID = "agents-import";

/** Codex reads the root→cwd AGENTS.md chain up to 32 KiB combined. */
export const CHAIN_BUDGET_BYTES = 32_768;
export const REGION_BUDGET_BYTES = 8_192;
export const ROOT_WARN_BYTES = 16_384;

const MAX_SCRIPTS_PER_APP = 8;

function cell(value: string | number | null): string {
  if (value === null || value === "") return "—";
  return String(value).replace(/\\/g, "\\\\").replace(/\|/g, "\\|");
}

function code(value: string | null): string {
  return value === null ? "—" : `\`${value}\``;
}

function scriptsFor(observation: ProjectObservation | null, path: string): string[] {
  const unit = observation?.units.find((entry) => entry.path === path);
  return Object.keys(unit?.scripts ?? {}).sort();
}

/** Render the region body (markdown, no markers). */
export function renderAgentsRegion(
  blueprint: BlueprintV2,
  observation: ProjectObservation | null,
): string {
  const lines: string[] = [
    `## groot project map — \`${blueprint.project.name}\``,
    "",
    "_Generated by `groot context sync` from groot.json; edit outside this block (hand edits inside it block the next sync instead of being overwritten)._",
    "",
    `- Topology: **${blueprint.project.topology}** · package manager: **bun** — never use npm, npx, yarn, or pnpm.`,
    "",
    "| App | Path | Kind | Framework | Dev port | Entry |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const app of blueprint.apps) {
    lines.push(
      `| ${cell(app.id)} | ${code(app.path)} | ${cell(app.kind)} | ${cell(app.framework)} | ${cell(app.port)} | ${code(app.entry)} |`,
    );
  }

  lines.push(
    "",
    "### Commands",
    "",
    "- `bun install` — install dependencies (one root `bun.lock`).",
  );
  for (const app of blueprint.apps) {
    const scripts = scriptsFor(observation, app.path).slice(0, MAX_SCRIPTS_PER_APP);
    if (scripts.length === 0) continue;
    const where = app.path === "." ? "" : ` --cwd ${app.path}`;
    lines.push(
      `- ${code(app.path)}: ${scripts.map((script) => `\`bun run${where} ${script}\``).join(", ")}`,
    );
  }

  if (blueprint.capabilities.length > 0) {
    lines.push("", "### Capabilities", "");
    for (const capability of blueprint.capabilities) {
      lines.push(
        `- **${capability.id}** on \`${capability.target}\` via \`${capability.recipe}\` (v${capability.recipeVersion})`,
      );
    }
  }

  if (blueprint.environment.length > 0) {
    lines.push("", "### Environment (names only — values live in gitignored files)", "");
    for (const contract of blueprint.environment) {
      const flags = [
        contract.scope,
        contract.sensitivity,
        contract.required ? "required" : "optional",
      ].join(", ");
      lines.push(
        `- \`${contract.name}\` → ${code(contract.storage)} (${flags}) — ${contract.description}`,
      );
    }
  }

  const decisions = blueprint.decisions.filter((decision) => decision.authority === "human");
  if (decisions.length > 0) {
    lines.push("", "### Decisions (human-confirmed)", "");
    for (const decision of decisions)
      lines.push(`- ${decision.topic}: ${decision.value} — ${decision.rationale}`);
  }

  lines.push(
    "",
    "### Working with groot",
    "",
    '- Facts for a task: `groot context --task "<goal>" --json`; project facts: `groot inspect --json`.',
    "- Change the project through previewable plans: `groot plan add <capability> --json` → review → `groot apply <planId> --json`.",
    "- Prove it works: `groot verify --json` (structural + build); add `--profile runtime,product-flow` for live checks.",
    "- Interrupted or wrong? `groot status --json`, `groot resume <operationId>`, `groot rollback <operationId> --dry-run`.",
    "- Never hand-edit `groot.json` or `groot.lock.json`; never commit `.groot/` or env files.",
  );
  return lines.join("\n");
}

/** The CLAUDE.md region: Claude Code's documented sharing pattern (`@AGENTS.md`). */
export function renderClaudeImport(): string {
  return "@AGENTS.md";
}
