/**
 * Test-only plan materializer (never imported by runtime code). It applies
 * exactly the action types recipes emit — file.write, precomputed and
 * deferred file.edit, deps.add, env.secret — in plan order, after checking
 * each step's expectation (a stale plan is an error here, as it is in the
 * executor), with the executor's own semantics where they matter (env.secret
 * reads assignments with the executor's predicate). Anything else is refused
 * rather than half-applied.
 */
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type {
  DepsAction,
  OperationPlan,
  PathExpectation,
  PlannedAction,
  SecretAction,
} from "../../contracts/plan.ts";
import { hasEnvAssignment } from "../../executor/secrets.ts";
import { hashFile } from "../../fs/hash.ts";
import { joinRel, resolveInProject } from "../../fs/paths.ts";
import { addEnvEntries, applyEdit } from "../../transforms/index.ts";
import { pointerToken } from "../plan-helpers.ts";

export interface Materialized {
  readonly applied: readonly string[];
  /** Values generated by env.secret steps — tests assert they never leak anywhere. */
  readonly secrets: readonly string[];
}

async function expectState(
  root: string,
  path: string,
  expect: PathExpectation,
  step: string,
): Promise<void> {
  if (expect.state === "produced") return;
  const hash = await hashFile(resolveInProject(root, path));
  if (expect.state === "absent" && hash !== null) {
    throw new Error(`${step}: ${path} exists, but the plan expected it to be absent (stale plan)`);
  }
  if (expect.state === "sha256" && hash !== expect.sha256) {
    throw new Error(`${step}: ${path} changed since planning (stale plan)`);
  }
}

function read(root: string, path: string): string | null {
  const absolute = resolveInProject(root, path);
  return existsSync(absolute) ? readFileSync(absolute, "utf8") : null;
}

function write(root: string, path: string, content: string): void {
  const absolute = resolveInProject(root, path);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, content);
}

async function applyDeps(root: string, action: DepsAction): Promise<void> {
  const path = joinRel(action.unit, "package.json");
  await expectState(root, path, action.expect, action.id);
  const ops = action.changes.map((change) => ({
    op: "set" as const,
    pointer: `/${change.dev ? "devDependencies" : "dependencies"}/${pointerToken(change.package)}`,
    value: change.to,
  }));
  write(root, path, applyEdit(read(root, path), { kind: "json", ops }, path));
}

/**
 * Generates the secret locally, exactly as the executor's env.secret step
 * does (core/executor/steps-files.ts): any assignment of the name — even an
 * empty `NAME=` — is left as it stands; otherwise the variable is appended.
 */
function applySecret(root: string, action: SecretAction): string | null {
  const current = read(root, action.path);
  if (current !== null && hasEnvAssignment(current, action.name)) return null;
  const value = randomBytes(32).toString("base64url");
  write(root, action.path, addEnvEntries(current, [{ name: action.name, value, comment: null }]));
  return value;
}

async function applyOne(root: string, action: PlannedAction): Promise<string | null> {
  switch (action.type) {
    case "file.write":
      await expectState(root, action.path, action.expect, action.id);
      write(root, action.path, action.content);
      if (action.executable) chmodSync(resolveInProject(root, action.path), 0o755);
      return null;
    case "file.edit": {
      await expectState(root, action.path, action.expect, action.id);
      const content =
        action.after !== null
          ? action.after.content
          : applyEdit(read(root, action.path), action.edit, action.path);
      write(root, action.path, content);
      return null;
    }
    case "deps.add":
      await applyDeps(root, action);
      return null;
    case "env.secret":
      return applySecret(root, action);
    default:
      throw new Error(`the test applier does not support ${action.type} (step ${action.id})`);
  }
}

export async function materializePlan(root: string, plan: OperationPlan): Promise<Materialized> {
  if (plan.project.root !== root) {
    throw new Error(`plan targets ${plan.project.root}, not ${root}`);
  }
  const applied: string[] = [];
  const secrets: string[] = [];
  for (const action of plan.actions) {
    const secret = await applyOne(root, action);
    if (secret !== null) secrets.push(secret);
    applied.push(action.id);
  }
  return { applied, secrets };
}
