/**
 * Blueprint contract — groot.json `version: 2`, the portable DESIRED state.
 *
 * v2 is a superset of the v1 manifest: `createdWith`, `conventions`, and
 * `scaffolds` keep their exact v1 meaning (the framework scaffolds Groot's
 * adapters generated), so consumers of the v1 fields keep working. New fields
 * describe the general project model (apps incl. adopted ones and single-app
 * roots), capabilities, decisions, environment contracts, verification
 * obligations, context settings, and the action policy.
 *
 * Migration from v1 is explicit and deterministic (core/blueprint/migrate.ts,
 * `groot migrate`); add/doctor keep reading v1 workspaces unchanged.
 */
import { z } from "zod";
import {
  ActionClass,
  Decision,
  EnvVarContract,
  IsoDate,
  PlanId,
  RelPath,
  Topology,
  UnitKind,
  UnitPath,
  VerificationContract,
} from "./common.ts";

/** groot.json version written by Groot v2. */
export const BLUEPRINT_VERSION = 2 as const;

/** groot.json version written by Groot v1 (still read by add/doctor). */
export const MANIFEST_V1_VERSION = 1 as const;

/**
 * groot.json's published schema URL. Per docs/stability.md it always describes
 * the newest version; the file accepts v1 and v2 documents (discriminated by
 * `version`), so v1 workspaces stay valid in editors.
 */
export const GROOT_JSON_SCHEMA_URL =
  "https://raw.githubusercontent.com/bloxy-studios/groot/main/schemas/groot.schema.json";

export const SLOT_IDS = ["web", "mobile", "desktop", "api", "backend"] as const;

export const FRAMEWORK_IDS = [
  "next",
  "sveltekit",
  "tanstack-start",
  "astro",
  "react-router",
  "nuxt",
  "vite",
  "expo",
  "react-native",
  "tauri",
  "electron",
  "elysia",
  "hono",
  "fastify",
  "convex",
  "supabase",
] as const;

/** A v1-shaped scaffold entry (identical semantics in v1 and v2). */
export const LegacyScaffold = z
  .object({
    slot: z.enum(SLOT_IDS),
    framework: z.enum(FRAMEWORK_IDS),
    path: z.string().min(1),
    generator: z.string().nullable(),
    port: z.number().int().min(1).max(65535).nullable(),
  })
  .strict();
export type LegacyScaffold = z.infer<typeof LegacyScaffold>;

export const Conventions = z
  .object({
    packagesNamespace: z.string().regex(/^@[a-z0-9-~][a-z0-9-._~]*$/),
  })
  .strict();

/** The v1 manifest (schemas/groot.v1.schema.json). */
export const ManifestV1 = z
  .object({
    $schema: z.string().optional(),
    version: z.literal(MANIFEST_V1_VERSION),
    createdWith: z.string().regex(/^create-groot@\d+\.\d+\.\d+(-[\w.]+)?$/),
    conventions: Conventions,
    scaffolds: z.array(LegacyScaffold),
  })
  .strict();
export type ManifestV1 = z.infer<typeof ManifestV1>;

/** An app/package/service Groot manages — generated by Groot or adopted as-is. */
export const BlueprintApp = z
  .object({
    /** Stable id used by capabilities ("web", "api", "root"). */
    id: z.string().regex(/^[a-z0-9][a-z0-9-]*$/),
    path: UnitPath,
    kind: UnitKind,
    framework: z.string().nullable(),
    packageName: z.string().nullable(),
    port: z.number().int().min(1).max(65535).nullable(),
    origin: z.enum(["generated", "adopted"]),
    /** Server/app entry used by recipes that mount into the app. */
    entry: RelPath.nullable(),
  })
  .strict();
export type BlueprintApp = z.infer<typeof BlueprintApp>;

export const CapabilityOptionValue = z.union([z.string(), z.number(), z.boolean()]);

export const BlueprintCapability = z
  .object({
    id: z.string(),
    recipe: z.string(),
    recipeVersion: z.string(),
    /** BlueprintApp id the capability is applied to. */
    target: z.string(),
    options: z.record(z.string(), CapabilityOptionValue),
    /** The plan that added it (plans and operations are 1:1 — a re-applied plan is a no-op). */
    addedBy: PlanId.nullable(),
    /** When that plan was made. */
    addedAt: IsoDate,
  })
  .strict();
export type BlueprintCapability = z.infer<typeof BlueprintCapability>;

export const ContextSettings = z
  .object({
    /** Managed sections live here (human content outside markers is preserved). */
    agentsMd: RelPath,
    /** Claude-compatible instructions file (imports AGENTS.md), or null to skip. */
    claudeMd: RelPath.nullable(),
    /** Skill projections to emit: Claude Code (.claude/skills) and agentskills hosts (.agents/skills). */
    skills: z.array(z.enum(["claude", "agents"])),
  })
  .strict();
export type ContextSettings = z.infer<typeof ContextSettings>;

/**
 * Action policy shared by every surface (CLI, MCP, task runners). A plan whose
 * declared action classes are not allowed is refused with a blocked decision.
 */
export const Policy = z
  .object({
    allow: z.array(ActionClass),
    /** Effects on provider accounts are never implicit. */
    external: z.enum(["deny", "ask"]),
  })
  .strict();
export type Policy = z.infer<typeof Policy>;

export const DEFAULT_POLICY: Policy = {
  allow: [
    "fs.create",
    "fs.edit",
    "fs.delete",
    "fs.move",
    "deps.change",
    "install",
    "generator",
    "command",
    "network",
    "git",
    "process",
  ],
  external: "ask",
};

export const ProjectSettings = z
  .object({
    name: z.string().min(1),
    topology: Topology,
    packageManager: z.literal("bun"),
    origin: z.enum(["created", "adopted", "migrated"]),
  })
  .strict();

export const BlueprintV2 = z.looseObject({
  $schema: z.string(),
  version: z.literal(BLUEPRINT_VERSION),
  createdWith: z.string().regex(/^create-groot@\d+\.\d+\.\d+(-[\w.]+)?$/),
  conventions: Conventions,
  scaffolds: z.array(LegacyScaffold),
  project: ProjectSettings,
  apps: z.array(BlueprintApp),
  capabilities: z.array(BlueprintCapability),
  decisions: z.array(Decision),
  environment: z.array(EnvVarContract),
  verification: z.array(VerificationContract),
  context: ContextSettings,
  policy: Policy,
});
export type BlueprintV2 = z.infer<typeof BlueprintV2>;

export const DEFAULT_CONTEXT: ContextSettings = {
  agentsMd: "AGENTS.md",
  claudeMd: "CLAUDE.md",
  skills: ["claude", "agents"],
};

/** Any groot.json Groot v2 can read, discriminated by version. */
export type AnyManifest = ManifestV1 | BlueprintV2;
